apiVersion: reshapr.io/v1alpha1
kind: SecretSource
metadata:
  name: tests-secrets
  annotations:
    reshapr.io/instance: reshapr-control-plane-ctrl.reshapr-system
    reshapr.io/organization: reshapr
spec:
  secrets:
    - name: github-token
      description: Token used to talk to the GitHub API
      type: ENDPOINT
      valuesFrom:
        secretRef: github-credentials
        tokenKey: token
        tokenHeaderKey: tokenHeader
    - name: acme-basic-auth
      description: Basic auth for the ACME backend
      type: ENDPOINT
      username: acme
      password: s3cr3t