# Logging levels
quarkus.log.level=INFO
%dev.quarkus.log.console.level=DEBUG
%dev.quarkus.log.category."io.reshapr.kubernetes".level=DEBUG
quarkus.log.category."io.javaoperatorsdk.operator"=INFO

# TODO: Workaround for accepting untrusted certs
quarkus.kubernetes-client.trust-certs=true

# Do not validate CRD presence as it requires cluster-admin privileges.
quarkus.operator-sdk.crd.validate=false
